server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost #设置cookie作用域
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: "jdbc:mysql://localhost:3306/yupi"
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    database: 0

mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: flag # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
knife4j:
  enable: true